license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Adds realistic cave-in mechanics to Minecraft. Stone, ores, and dirt-like blocks can collapse when mined, creating dramatic progressive cave-ins with screen shake effects.
'''
authors="ccdelic"

[[mixins]]
config="collapsingcaves.mixins.json"

[[mixins]]
config="collapsingcaves.client.mixins.json"
clientOnly=true

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[26.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
